// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "namespace", Target = "~N:ForumSystem.Web.ViewModels.Home")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel.CommentsCount")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel.Content")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel.CreatedOn")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel.ShortContent")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel.Title")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel.UserUserName")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel.Description")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel.ImageUrl")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel.PostsCount")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel.Title")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel.Url")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Home.IndexViewModel.Categories")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Posts.PostCreateInputModel.CategoryId")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Posts.PostCreateInputModel.Content")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Posts.PostCreateInputModel.Title")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Categories.PostInCategoryViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Home.IndexCategoryViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Home.IndexViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Posts.PostCreateInputModel")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification", Justification = "<Pending>")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "namespace", Target = "~N:ForumSystem.Web.ViewModels.Categories")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.CategoryDropDownViewModel.Id")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Categories.CategoryDropDownViewModel.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Categories.CategoryDropDownViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Categories.CategoryViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "namespace", Target = "~N:ForumSystem.Web.ViewModels.Posts")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Posts.PostViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~M:ForumSystem.Web.ViewModels.Settings.SettingViewModel.CreateMappings(AutoMapper.IProfileExpression)")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "namespace", Target = "~N:ForumSystem.Web.ViewModels.Settings")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Administration.Dashboard.IndexViewModel.SettingsCount")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.ErrorViewModel.RequestId")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.ErrorViewModel.ShowRequestId")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Settings.SettingsListViewModel.Settings")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Settings.SettingViewModel.Id")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Settings.SettingViewModel.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Settings.SettingViewModel.NameAndValue")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "member", Target = "~P:ForumSystem.Web.ViewModels.Settings.SettingViewModel.Value")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Administration.Dashboard.IndexViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.ErrorViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Settings.SettingsListViewModel")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1027:Use tabs correctly", Justification = "<Pending>", Scope = "type", Target = "~T:ForumSystem.Web.ViewModels.Settings.SettingViewModel")]
